name: build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  std-ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install python and scipy
        run: sudo apt-get install python3-scipy
      - name: Run tests
        run: cargo test
